### ISSUE TITLE
Systemauswahl

### ISSUE THREAD

**Issue by ThomasPause** [hitontology/database-frontend#1]
We need a frontend for our database that conforms to our system specification at https://github.com/hitontology/database-frontend/issues/2.
For this, the first idea is to use an existing approach.
Investigate!

**Comment by KonradHoeffner** [comment]
I am investigating the Flask framework for Python.
There is also the https://github.com/dpgaspar/Flask-AppBuilder.

**Comment by KonradHoeffner** [comment]
Developing a prototype using Flask-AppBuilder, see https://flask-appbuilder.readthedocs.io.

**Comment by KonradHoeffner** [comment]
Flask-AppBuilder can show other tables using their labels as a multi selection field and allows search and CRUD, so a custom solution using Flask-AppBuilder is the choice.
