### ISSUE TITLE
EHR HL7 FM various features are twice in classified to select

### ISSUE THREAD

**Issue by VerenaDornauer** [hitontology/database-frontend#21]
@KonradHoeffner 

The classifier "Manage Patient History" is twice to select. Which one belongs to the EHR HL7 FM? Not differentiable at the first sight and also not at the second :)...

same with "Manage Clinical Documentation"

same with "Manage Administrative Transaction Processing"

same with "Manage Results of Diagnostic Tests"

**Comment by KonradHoeffner** [comment]
There are two problems:

1. these exist in hito.ttl (?) and in hl7: delete classifieds in hito.ttl and update references to hl7
2. the label shown in the frontend does not show the catalogue, so it is impossible to know, which one to select if a label occurs twice

**Comment by KonradHoeffner** [comment]
OK they aren't in hito.ttl but in the Dickinson catalogue dickinson.ttl. Should that one be deleted?

**Comment by KonradHoeffner** [comment]
I added the catalogue name to the classified labels now so that the user now has the information necessary to decide which one to chose.
As for the removal of the duplicates, this is an ontology issue and has been split off into https://github.com/hitontology/ontology/issues/45.

**Comment by KonradHoeffner** [comment]
Note: This may not be immediately reflected in the online version until that one is rebuild.

**Comment by KonradHoeffner** [comment]
The change is now live on https://hitontology.eu/database-frontend.
