### ISSUE TITLE
Error Code Software System hinzufügen Database

### ISSUE THREAD

**Issue by MichelleBindel** [hitontology/database-frontend#22]
Diese Fehlermeldung erscheint und das Software Product wird nicht hinzugefügt:
<img width="426" alt="Algemeiner Fehler class 'sqlalchemy exc DataError'" src="https://user-images.githubusercontent.com/43496783/106137913-b621de80-616b-11eb-8279-d54853624274.png">

Wenn ich die folgende Eintragung machen möchte:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/43496783/106137869-a3a7a500-616b-11eb-9778-7ff84c9514e9.png">

Es klappt wenn ich bei der Database die Eintragung weglasse, anscheinend klappt da mit den neuen DB-Systemen noch nicht alles.

**Comment by VerenaDornauer** [comment]
Liegt glaube ich daran, dass aktuell weder der Application System Katalog von WHOdhi noch von BB integriert ist. Bei mir scheint das selbe auf.

**Comment by KonradHoeffner** [comment]
Der genaue Fehler auf dem Server ist:

```
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10)
database-frontend_1  | 
database-frontend_1  | [SQL: INSERT INTO swp_has_databasesystem (swp_suffix, db_suffix) VALUES (%(swp_suffix)s, %(db_suffix)s)]
database-frontend_1  | [parameters: {'swp_suffix': 'test123123123', 'db_suffix': 'MicrosoftSqlServer'}]
```
Ich habe vor kurzem die Spalte in der Datenbank von 10 auf 20 Characters vergrößert, damit die neuen längeren Datenbanksysteme auch mit reinpassen. Irgendwie denkt das Frontend aber noch, dass die Spalte nur 10 Characters lang ist.

Vielleicht cached das Flask irgendwie das alte Schema?

**Comment by KonradHoeffner** [comment]
Es lag gar nicht am Frontend, sondern es war ein Datenbankfehler. Ich hatte zwar den Primärschlüssel auf 20 verlängert, aber vergessen auch den Fremdschlüssel darauf zu verlängern. Das habe ich korrigiert und jetzt geht es. Commit https://github.com/hitontology/database/commit/bc4be299bc9934d3a256c75502ac8d5f253134bf hält das für später fest.
