### ISSUE TITLE
features with numbers in front (EhrSfmFeatureCatalogue)

### ISSUE THREAD

**Issue by MichelleBindel** [hitontology/database-frontend#28]
Some features from the EhrSfmFeatureCatalogue are displayed with their numbering in front.

Examples:
<img width="417" alt="Screenshot at Apr 13 15-45-21" src="https://user-images.githubusercontent.com/43496783/114567985-06d9ab80-9c74-11eb-9b6d-4ce8ea80ec5d.png">
<img width="736" alt="Screenshot at Apr 13 16-20-23" src="https://user-images.githubusercontent.com/43496783/114568133-2a9cf180-9c74-11eb-9ab4-30c5651469f8.png">

**Comment by KonradHoeffner** [comment]
Ja das ist Absicht, das habe ich in die Labels rein genommen weil das mal jemand haben wollte, ich weiß aber nicht mehr wer und wann.

**Comment by MichelleBindel** [comment]
ah ok!

**Comment by KonradHoeffner** [comment]
P.S.: Wenn du die Labels ohne Nummern brauchst, kannst du die skos:altLabel Werte nehmen in diesem Fall. Vielleicht finden wir auch eine generische Lösung, wenn das stört.
